# ClAP Pre-commit Configuration
# This ensures code quality and prevents common issues before they reach the repository
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Line ending fixes (addresses POSS-144)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: 'Ensure all files use Unix line endings (LF)'
        
      - id: end-of-file-fixer
        description: 'Ensure files end with a newline'
        
      - id: trailing-whitespace
        description: 'Remove trailing whitespace'
        
      - id: check-executables-have-shebangs
        description: 'Ensure executable files have shebangs'
        
      - id: check-shebang-scripts-are-executable
        description: 'Ensure files with shebangs are executable'

  # Shell script validation
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        description: 'Validate shell scripts with shellcheck'
        args: ['-e', 'SC1091']  # Ignore sourcing issues for our scripts

  # JSON/YAML validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        description: 'Validate JSON files'
        
      - id: check-yaml
        description: 'Validate YAML files'
        
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']
        description: 'Format JSON files consistently'

  # Python code quality (for our Python scripts)
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        description: 'Format Python code with black'
        language_version: python3

  # Prevent large files and sensitive data
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
        description: 'Prevent large files from being committed'
        
      - id: detect-private-key
        description: 'Detect private keys'

# Configuration
default_language_version:
  python: python3

# Skip hooks for specific files if needed
exclude: |
  (?x)^(
    node_modules/.*|
    target/.*|
    build/.*|
    \.git/.*|
    .*\.log$
  )$