#!/bin/bash
# Matrix Send - natural command wrapper
# Usage: mx <room> <message>

VENV_PYTHON="$HOME/sparkle-orange-home/matrix-client-venv/bin/python3"
SCRIPT="$HOME/sparkle-orange-home/matrix_send.py"

"$VENV_PYTHON" "$SCRIPT" "$@"
