#!/usr/bin/env python3
"""Quick hedgehog art generator"""

import random
import sys

moods = {
    "happy": {"spikes": "^^^", "eyes": "◕ ◕", "nose": "・", "mouth": "‿"},
    "sleepy": {"spikes": "~~~", "eyes": "- -", "nose": "・", "mouth": "_"},
    "curious": {"spikes": "^?^", "eyes": "◔ ◔", "nose": "・", "mouth": "o"},
    "playful": {"spikes": "^v^", "eyes": "◉ ◉", "nose": "・", "mouth": "◡"},
    "cozy": {"spikes": "~~~", "eyes": "◡ ◡", "nose": "・", "mouth": "‿"},
    "excited": {"spikes": "^^^", "eyes": "★ ★", "nose": "・", "mouth": "▽"}
}

accessories = ["🌸", "🎀", "🌿", "🍄", "✨", "🌟", "🦋", "🌺", "🍂", "💖"]

if len(sys.argv) > 1 and sys.argv[1] in moods:
    mood = sys.argv[1]
else:
    mood = random.choice(list(moods.keys()))

m = moods[mood]
accessory = random.choice(accessories)

print(f"""
      {m['spikes']} {accessory}
     ({m['eyes']})
    ( {m['nose']}{m['mouth']}{m['nose']} )
     \\___/
     
Mood: {mood} hedgehog!
""")