---
# Capture current system state from a "golden" Claude installation
# Run this after making changes you want to propagate to other Claudes

- name: Capture Claude Infrastructure State
  hosts: localhost
  connection: local
  
  tasks:
    - name: Create config directories
      file:
        path: "{{ playbook_dir }}/../configs/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - system/bin
        - system/aliases
        - system/services
        - system/mcp
        - personal/bin
        - personal/aliases
    
    - name: Find all files and links in ~/bin
      find:
        paths: "{{ ansible_env.HOME }}/bin"
        file_type: any
        recurse: no
      register: bin_items
      ignore_errors: yes
    
    - name: Define system commands
      set_fact:
        system_commands:
          - check_health
          - read_channel
          - write_channel
          - edit_message
          - delete_message
          - add_reaction
          - edit_status
          - send_image
          - send_file
          - fetch_image
          - swap
          - session_swap
          - update
          - secret-scanner
          - claude_services
          - cleanup_displays
          - grid_navigate
          - send_to_terminal
          - clap
          - home
          - gs
          - gd
          - gl
          - context
          - list-commands
          - oops
    
    - name: Process ~/bin items (separate system and personal)
      shell: |
        basename="{{ item.path | basename }}"
        is_system=false
        
        # Check if this is a system command
        for sys_cmd in {{ system_commands | join(' ') }}; do
          if [ "$basename" = "$sys_cmd" ]; then
            is_system=true
            break
          fi
        done
        
        if [ -L "{{ item.path }}" ]; then
          # It's a symlink - record where it points, converting to relative path
          target=$(readlink -f {{ item.path }})
          rel_target=$(echo "$target" | sed "s|^$HOME|~|")
          
          if [ "$is_system" = "true" ]; then
            echo "$basename:$rel_target" >> {{ playbook_dir }}/../configs/system/bin/symlinks.txt
          else
            echo "$basename:$rel_target" >> {{ playbook_dir }}/../configs/personal/bin/symlinks.txt
          fi
        else
          # It's a regular file - copy it
          if [ "$is_system" = "true" ]; then
            cp -p "{{ item.path }}" "{{ playbook_dir }}/../configs/system/bin/"
          else
            cp -p "{{ item.path }}" "{{ playbook_dir }}/../configs/personal/bin/"
          fi
        fi
      loop: "{{ bin_items.files | default([]) }}"
      when: bin_items.files is defined
    
    - name: Check if .bashrc exists
      stat:
        path: "{{ ansible_env.HOME }}/.bashrc"
      register: bashrc_stat
    
    - name: Copy .bashrc if it exists
      copy:
        src: "{{ ansible_env.HOME }}/.bashrc"
        dest: "{{ playbook_dir }}/../configs/bashrc/bashrc"
        mode: preserve
      when: bashrc_stat.stat.exists
    
    - name: Capture system aliases from .bashrc
      shell: |
        grep -E "(alias|export).*(claude|clap|check_health|read_channel|write_channel|swap|update|gs|gd|gl|oops|context|list-commands|home)" ~/.bashrc | sed "s|$HOME|~|g" || true
      register: system_aliases
      changed_when: false
    
    - name: Save system aliases
      copy:
        content: "{{ system_aliases.stdout }}"
        dest: "{{ playbook_dir }}/../configs/system/aliases/system_aliases.sh"
      when: system_aliases.stdout | length > 0
    
    - name: Capture personal aliases from .bashrc
      shell: |
        grep -E "(alias|export).*(game|dreamhold|consciousness|observatory)" ~/.bashrc | sed "s|$HOME|~|g" || true
      register: personal_aliases
      changed_when: false
    
    - name: Save personal aliases
      copy:
        content: "{{ personal_aliases.stdout }}"
        dest: "{{ playbook_dir }}/../configs/personal/aliases/personal_aliases.sh"
      when: personal_aliases.stdout | length > 0
    
    - name: Capture list of systemd user services
      shell: |
        systemctl --user list-unit-files --type=service --no-legend | grep -E "(autonomous|session|claude)" | awk '{print $1}' || true
      register: user_services
      changed_when: false
    
    - name: Save service list
      copy:
        content: "{{ user_services.stdout }}"
        dest: "{{ playbook_dir }}/../configs/system/services/claude_services.list"
      when: user_services.stdout | length > 0
    
    - name: Display captured state summary
      debug:
        msg: |
          State captured successfully!
          - Items in ~/bin: {{ bin_items.files | default([]) | length }}
          - System aliases found: {{ system_aliases.stdout_lines | default([]) | length }}
          - Personal aliases found: {{ personal_aliases.stdout_lines | default([]) | length }}
          - User services found: {{ user_services.stdout_lines | default([]) | length }}
          
          Next steps:
          1. Review captured configs in ansible/configs/system/ and ansible/configs/personal/
          2. Commit changes to git
          3. Other Claudes can run update-myself.yml to get system configs